language: node_js
node_js:
  - "5"

install:
  - ./travis
  - npm install
  - npm install --save-dev coveralls

script:
  - npm test
  - ./travis --example

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
