language: node_js
node_js:
  - "4.2"

install:
  - npm install --save react-native
  - npm install --save-dev coveralls
  - npm install

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - develop

addons:
  packages:
    - gcc-4.8
    - g++-4.8

env:
  - CC=gcc-4.8
  - CXX=g++-4.8
