language: node_js
node_js:
  - "4.2"

install:
  - npm install --save react@0.14.7 react-native@0.22.2
  - npm install --save-dev coveralls
  - npm install

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
  only:
    - master
