#!/bin/bash

# Remove old library folder
if [ -d react-native-mock ]; then
	rm -Rf react-native-mock
fi

# Check & install react-native-mock
if [ ! -d node_modules/react-native-mock ]; then
	npm install --only=dev
fi

# Copy react-native-mock to project folder
cp -Rf node_modules/react-native-mock/build react-native-mock
cp node_modules/react-native-mock/LICENSE react-native-mock/

# Update dependencies
node configure.js
if [ "$1" != "--local" ]; then
	npm publish
	git checkout -- package.json
fi

echo 'Done'
