#!/bin/bash

if [ "$1" == "--example" ]; then

# run example test
mv node_modules/ Example/
cd Example
npm install && npm install --only=dev
npm test
mv node_modules/ ..
cd ..

else

# run before install in travis-ci
sed -i 's/"jest-cli"/"react": "^0.14.7","react-native": "^0.22.2","jest-cli"/g' package.json

npm install --only=dev
node configure.js

fi
