#!/bin/bash

if [ "$1" == "--example" ]; then

# run example test
mv node_modules/ Example/
cd Example
npm install && npm install --only=dev
npm test
mv node_modules/ ..
cd ..

else

# run before install in travis-ci
npm install react react-native
npm install --only=dev
node configure.js

fi
